version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres:13"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/auth_api_data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d auth_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: always

  redis:
    container_name: redis
    image: redis:7
    env_file:
      - ./.env
    volumes:
      - $HOME/redis/data:/var/lib/redis/data

  auth:
    container_name: auth
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/configs:/etc/nginx/conf.d:ro
#    depends_on:
#      - auth
#    ports:
#      - "80:80"
