"""oauth account table

Revision ID: 2fea3aa3ce2e
Revises: 3f14307048e0
Create Date: 2023-06-17 10:57:48.310541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fea3aa3ce2e'
down_revision = '3f14307048e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oauth_user_login', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
