"""add partitioning users table

Revision ID: 5ed4b3796ccb
Revises: 24ec1405a840
Create Date: 2023-06-06 09:24:55.299476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed4b3796ccb'
down_revision = '24ec1405a840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_partitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partition_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partition_id', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'users_partitions', ['partition_id'], ['id'])

    # Create trigger to insert into user_partitions table
    op.execute("""
    CREATE OR REPLACE FUNCTION insert_user_partition()
    RETURNS TRIGGER AS $$
    BEGIN
    INSERT INTO users_partitions (id, partition_id) 
    VALUES (NEW.id, NEW.partition_id);
    RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER insert_user_partition_trigger
    AFTER INSERT ON users
    FOR EACH ROW
    EXECUTE FUNCTION insert_user_partition();
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION users_insert_trigger()
    RETURNS TRIGGER AS $$
    BEGIN
    INSERT INTO users_partitions VALUES (NEW.*);
    RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER users_insert_trigger
    BEFORE INSERT ON users
    FOR EACH ROW
    EXECUTE FUNCTION users_insert_trigger();
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('partition_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # Remove partitioning from users table
    op.execute("""
    DROP TRIGGER users_insert_trigger ON users;
    DROP FUNCTION users_insert_trigger();
    DROP TABLE users_partitions;
    """)

    # Remove trigger and function for user_partitions table
    op.execute("""
    DROP TRIGGER insert_user_partition_trigger ON users;
    DROP FUNCTION insert_user_partition();
    """)

    # Remove user_partitions table and partition_id column from users table
    op.drop_table('users_partitions')
    op.drop_column('users', 'partition_id')
    # ### end Alembic commands ###
