"""oauth account table

Revision ID: 8e9f5af4eed4
Revises: 3f14307048e0
Create Date: 2023-06-16 23:13:25.324466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e9f5af4eed4'
down_revision = '3f14307048e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oauth_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('oauth_email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'oauth_id')
    )
    with op.batch_alter_table('login_history_y2023m02', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m02_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m02_user_id_idx')

    op.drop_table('login_history_y2023m02')
    with op.batch_alter_table('login_history_y2023m05', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m05_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m05_user_id_idx')

    op.drop_table('login_history_y2023m05')
    with op.batch_alter_table('login_history_y2023m04', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m04_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m04_user_id_idx')

    op.drop_table('login_history_y2023m04')
    with op.batch_alter_table('login_history_y2023m01', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m01_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m01_user_id_idx')

    op.drop_table('login_history_y2023m01')
    with op.batch_alter_table('login_history_y2023m12', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m12_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m12_user_id_idx')

    op.drop_table('login_history_y2023m12')
    with op.batch_alter_table('login_history_y2023m06', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m06_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m06_user_id_idx')

    op.drop_table('login_history_y2023m06')
    with op.batch_alter_table('login_history_y2023m09', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m09_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m09_user_id_idx')

    op.drop_table('login_history_y2023m09')
    with op.batch_alter_table('login_history_y2023m07', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m07_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m07_user_id_idx')

    op.drop_table('login_history_y2023m07')
    with op.batch_alter_table('login_history_y2023m11', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m11_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m11_user_id_idx')

    op.drop_table('login_history_y2023m11')
    with op.batch_alter_table('login_history_y2023m10', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m10_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m10_user_id_idx')

    op.drop_table('login_history_y2023m10')
    with op.batch_alter_table('login_history_y2023m08', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m08_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m08_user_id_idx')

    op.drop_table('login_history_y2023m08')
    with op.batch_alter_table('login_history_y2023m03', schema=None) as batch_op:
        batch_op.drop_index('login_history_y2023m03_auth_datetime_idx')
        batch_op.drop_index('login_history_y2023m03_user_id_idx')

    op.drop_table('login_history_y2023m03')
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_index('idx_login_history_auth_datetime')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_login_history_auth_datetime', ['auth_datetime'], unique=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('login_history_y2023m03',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m03_pkey')
    )
    with op.batch_alter_table('login_history_y2023m03', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m03_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m03_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m08',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m08_pkey')
    )
    with op.batch_alter_table('login_history_y2023m08', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m08_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m08_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m10',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m10_pkey')
    )
    with op.batch_alter_table('login_history_y2023m10', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m10_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m10_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m11',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m11_pkey')
    )
    with op.batch_alter_table('login_history_y2023m11', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m11_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m11_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m07',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m07_pkey')
    )
    with op.batch_alter_table('login_history_y2023m07', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m07_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m07_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m09',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m09_pkey')
    )
    with op.batch_alter_table('login_history_y2023m09', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m09_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m09_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m06_pkey')
    )
    with op.batch_alter_table('login_history_y2023m06', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m06_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m06_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m12',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m12_pkey')
    )
    with op.batch_alter_table('login_history_y2023m12', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m12_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m12_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m01',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m01_pkey')
    )
    with op.batch_alter_table('login_history_y2023m01', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m01_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m01_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m04',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m04_pkey')
    )
    with op.batch_alter_table('login_history_y2023m04', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m04_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m04_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m05',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m05_pkey')
    )
    with op.batch_alter_table('login_history_y2023m05', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m05_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m05_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.create_table('login_history_y2023m02',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'auth_datetime', name='login_history_y2023m02_pkey')
    )
    with op.batch_alter_table('login_history_y2023m02', schema=None) as batch_op:
        batch_op.create_index('login_history_y2023m02_user_id_idx', ['user_id'], unique=False)
        batch_op.create_index('login_history_y2023m02_auth_datetime_idx', ['auth_datetime'], unique=False)

    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
